INSERT INTO entries (title,
                                            content,
                                            mood,
                                            date_created,
                                            category_id,
                                            user_id
                                            ) VALUES 
  ('Atque maiores atque maiores perspiciatis.',
  'Alias occaecati qui voluptatem necessitatibus non est tenetur. Ut deleniti enim nihil. Repellendus sit alias soluta sed enim est maxime. Incidunt distinctio eius tenetur repudiandae dignissimos voluptates incidunt sint dignissimos. Molestiae voluptatum nostrum quo. Qui autem autem soluta quae.',
  2,
  NOW() -  interval '34379 hours',
  1,
  1),
  ('Enim laborum neque optio tempora temporibus omnis.',
  'Eum aperiam qui ratione eius impedit consequatur eveniet amet ratione. Qui nesciunt eius et tempore velit et ab sint voluptatem. Doloribus aspernatur dolorem quos dolores. Commodi deserunt quas necessitatibus aut sint sint ipsam.',
  3,
  NOW() -  interval '27835 hours',
  1,
  1),
  ('Et ipsum et fugit omnis.',
  'Commodi quaerat id est numquam asperiores esse ad. Ut quos et repellat est porro voluptatibus. Voluptatem vel deserunt fugit qui aliquid et doloremque nemo. Voluptatem quaerat architecto vel consequatur. Iusto quisquam qui consequatur neque est.',
  4,
  NOW() -  interval '7315 hours',
  1,
  1),
  ('Recusandae et perferendis fuga recusandae natus voluptatem.',
  'Voluptatem rerum excepturi voluptatem in quisquam. Nihil quidem maiores optio cupiditate sed voluptates. Nulla dolores quis hic blanditiis beatae. Sit rerum eveniet velit. Non non asperiores assumenda quasi. Quis qui numquam harum fugiat eligendi ducimus illo voluptatem.',
  3,
  NOW() -  interval '755 hours',
  1,
  1),
  ('Pariatur qui non ut dolor et.',
  'Ea est tempora ut non iure ad doloribus sed. Commodi rem deserunt velit. Labore pariatur numquam autem nostrum voluptas voluptas. In aperiam voluptatem quidem rem.',
  1,
  NOW() -  interval '11041 hours',
  1,
  1);