INSERT INTO Question (Question, RoundNumber, Hint, OptionA, OptionB, OptionC, OptionD, Correct_Option, Created_At)
VALUES
  ('What is the square root of a fish?', 1, 'Fish come in many shapes and sizes, but they are known for something specific.', '2', 'Fish', '42', '√(-1)', 'B', NOW()),
  ('If you have 3 apples and you take away 2, how many apples do you have left?', 1, 'This question plays with the concept of ownership.', '0', '1', '2', '3', 'B', NOW()),
  ('What has keys but can''t open locks?', 1, 'This item is often found in homes and offices.', 'A door', 'Keyboard', 'Typewriter', 'Piano', 'D', NOW()),
  ('Which is the odd one out?', 1, 'Consider the category or common characteristics of the items.', 'Apple', 'Banana', 'Orange', 'Grape', 'C', NOW()),
  ('How many sides does a circle have?', 1, 'Think geometrically, but don''t focus on straight lines.', '0', '1', '2', 'Infinite', 'B', NOW()),
  ('If a plane crashes on the border between the U.S. and Canada, where do you bury the survivors?', 1, 'This is a tricky question involving the geography of a crash.', 'In the U.S.', 'In Canada', 'Nowhere, survivors are alive', 'In an international cemetery', 'C', NOW()),
  ('What gets wetter as it dries?', 1, 'It''s related to an everyday item and the action it performs.', 'Towel', 'Sponge', 'Soap', 'Raincoat', 'A', NOW()),
  ('Which planet is known as the "Red Planet"?', 1, 'Look to the skies and identify the planet with a distinct color.', 'Venus', 'Jupiter', 'Mars', 'Saturn', 'C', NOW()),
  ('What comes once in a minute, twice in a moment, but never in a thousand years?', 1, 'This one is about time and a specific letter''s occurrence.', 'The letter "M"', 'The letter "E"', 'The letter "O"', 'The letter "N"', 'A', NOW()),
  ('If a rooster lays an egg on a triangular roof, which way does the egg roll?', 1, 'Focus on the unique situation described and its implications.', 'Left', 'Right', 'It doesn''t roll, roosters don''t lay eggs', 'Down', 'C', NOW()),
  ('How can a man go eight days without sleep?', 1, 'It''s not about sleeping patterns but a clever trick with days.', 'He sleeps at night', 'He takes power naps', 'He sleeps during the day', 'He only sleeps at night', 'D', NOW()),
  ('What has an endless supply of letters but starts empty?', 1, 'It''s not about paper or mail but a fundamental concept.', 'Mailbox', 'Alphabet', 'Post Office', 'Mailman', 'B', NOW()),
  ('What has a heart that doesn''t beat?', 1, 'It''s not a living thing but is often found on walls.', 'Clock', 'Person', 'Deer', 'Artichoke', 'D', NOW()),
  ('What has a neck but no head?', 1, 'Think about a container with a long neck.', 'Giraffe', 'Turtle Neck Sweater', 'Shirt', 'Bottle', 'D', NOW()),
  ('What is as light as a feather yet the strongest person can''t hold it for more than a few minutes?', 1, 'It''s not tangible but involves a momentary experience.', 'Air', 'Breath', 'Laughter', 'Hope', 'B', NOW()),
  ('What is full of holes but still holds water?', 1, 'It''s not a physical object but something you might use in the kitchen.', 'Sponge', 'Net', 'Strainer', 'Cloud', 'A', NOW()),
  ('What has a face and two hands but no arms or legs?', 1, 'You look at it daily to know the time.', 'Clock', 'Mirror', 'Sun', 'Compass', 'A', NOW()),
  ('What has a head, a tail, is brown, and has no legs?', 1, 'It''s often found outdoors.', 'Snake', 'Stick', 'Cigar', 'Worm', 'D', NOW()),
  ('What has one eye but can''t see?', 1, 'It''s a tool for crafting.', 'Cyclops', 'Needle', 'Camera', 'Telescope', 'B', NOW()),
  ('The more you take, the more you leave behind. What am I?', 1, 'It''s about your journey and interactions.', 'Footsteps', 'Breath', 'Mist', 'Echo', 'A', NOW()),
  ('What belongs to you but is used more by others?', 1, 'It''s a resource you invest and spend.', 'Your name', 'Your car', 'Your time', 'Your money', 'A', NOW()),
  ('I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?', 1, 'It''s about the invisible impact of nature.', 'Echo', 'Music', 'Whisper', 'Thunder', 'A', NOW()),
  ('I am taken from a mine, and shut up in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?', 1, 'You draw with it.', 'Gold', 'Diamond', 'Pencil lead', 'Coal', 'C', NOW()),
  ('What can be cracked, made, told, and played?', 1, 'You find me in a house.', 'Joke', 'Code', 'Egg', 'Record', 'A', NOW()),
  ('I am always hungry. I must always be fed. The finger I lick will soon turn red. What am I?', 1, 'More I am fed the bigger I get.', 'Dog', 'Fire', 'Cat', 'Baby', 'B', NOW()),
  ('What can travel around the world while staying in a corner?', 1, 'People collect me.', 'The flu', 'Earth', 'A stamp', 'Satellite', 'C', NOW()),
  ('If a cat is black and a cat is white, what kind of cat doesn''t exist?', 1, 'It''s a play on colors.', 'Gray cat', 'Invisible cat', 'Rainbow cat', 'Striped cat', 'A', NOW()),
  ('What has cities but no houses, forests but no trees, and rivers but no water?', 1, 'It''s a representation.', 'Map', 'Book', 'Globe', 'Dictionary', 'A', NOW()),
  ('What is always in front of you but can''t be seen?', 1, 'It''s a moment in time.', 'Future', 'Past', 'Present', 'Memory', 'A', NOW()),
  ('What has teeth but can''t bite?', 1, 'It''s used in clothing.', 'Zipper', 'Comb', 'Saw', 'Key', 'A', NOW()),
  ('What can run but never walks, has a mouth but never talks?', 1, 'It helps you keep time.', 'Wind', 'River', 'Clock', 'Fire', 'C', NOW()),
  ('What is the absolute last thing both men and women take off before getting into bed?', 1, 'Think literally', 'Hat', 'Shoes', 'Socks', 'Their feet off the floor', 'D', NOW());
INSERT INTO Question (Question, RoundNumber, Hint, OptionA, OptionB, OptionC, OptionD, Correct_Option, Created_At)
VALUES
  ('What do you call a group of wolves?', 2, 'Think about their behavior', 'A herd', 'A school', 'A pack', 'A flock', 'C', NOW()),
  ('The maker does not want it, the buyer does not use it, and the user does not see it.', 2, 'Think about the context and purpose of the item mentioned.', 'Coffin', 'Notebook', 'Pen', 'Desk', 'A', NOW()),
  ('What gas do plants absorb from the air?', 2, 'As essential gas.', 'Carbon Dioxide', 'Oxygen', 'Nitrogen', 'Helium', 'A', NOW()),
  ('What''s 2 + 2?', 2, 'Simple addition.', '4', '3', '5', '6', 'A', NOW()),
  ('Break it and it is better, immediately set, and harder to break again. What am I?', 2, 'Consider the context of something breaking and becoming better.', 'Glass', 'Bone', 'A record', 'Mirror', 'C', NOW()),
  ('What''s the chemical symbol for water?', 2, 'Two parts hydrogen one part oxygen', 'CH4', 'O2', 'CO2', 'H2O', 'D', NOW()),
  ('What''s the largest planet in our solar system?', 2, 'Think about the planets'' sizes.', 'Mars', 'Earth', 'Jupiter', 'Saturn', 'C', NOW()),
  ('What''s the smallest even prime number?', 2, 'A unique characteristic.', '2', '1', '3', '4', 'A', NOW()),
  ('What is 147 apples plus 68 oranges?', 2, 'Consider the composition of the question and its straightforwardness.', 'A lot of fruit', '215 fruits', '147 apples and 68 oranges', 'Fruit salad', 'C', NOW()),
  ('If you give me food I will grow. If you give me water I will die. Who or what am I?', 2, 'Think about elements that need food to sustain and grow, and those that perish when exposed to water.', 'Plant', 'Animal', 'Rock', 'Fire', 'D', NOW()),
  ('What''s the chemical symbol for oxygen?', 2, 'An essential gas.', 'H2O', 'O2', 'CO2', 'O', 'B', NOW()),
  ('The more you have of it, the less you see. What is it?', 2, 'Think about a condition where the absence of something allows another to become more apparent.', 'Light', 'Vision', 'Darkness', 'Knowledge', 'C', NOW()),
  ('How many planets are there in our solar system?', 2, 'Include Pluto if you must.', '7', '9', '10', '8', 'D', NOW()),
  ('What is so fragile that when you say its name you break it?', 2, 'Consider the impact of sound on a particular concept.', 'Mirror', 'Glass', 'Feather', 'Silence', 'D', NOW()),
  ('How many sides does a hexagon have?', 2, 'It''s in the name.', '5', '7', '6', '8', 'C', NOW()),
  ('Who wrote "Romeo and Juliet"?', 2, 'Classic playwright.', 'William Shakespeare', 'Charles Dickens', 'Jane Austen', 'Mark Twain', 'A', NOW()),
  ('How many years are in a decade?', 2, 'A portion of a century.', '5', '20', '10', '100', 'C', NOW()),
  ('What''s the opposite of "empty"?', 2, 'Think about containers.', 'Half', 'Full', 'Light', 'Dense', 'B', NOW()),
  ('How many sides does a triangle have?', 2, 'Classic geometry.', '4', '3', '5', '6', 'B', NOW()),
  ('What is the square root of 16?', 2, 'A perfect square.', '4', '8', '2', '64', 'A', NOW()),
  ('What orchestral device is not blown, bowed, plucked or struck?', 2, 'Think about who directs the performance without directly interacting with the instruments.', 'The conductor''s baton', 'Triangle', 'Cello', 'Trombone', 'A', NOW());
INSERT INTO Question (Question, RoundNumber, Hint, OptionA, OptionB, OptionC, OptionD, Correct_Option, Created_At)
VALUES
  ('What is the meaning of life, the universe, and everything?', 3, 'The answer is as elusive as the question.', '42', 'Infinite possibilities', 'Love', 'A mystery', 'D', NOW()),
  ('July 4th is the day that Americans celebrate "Independence Day." Do the British have a fourth of July in England?', 3, 'Think about the literal interpretation of the question', 'Yes, they do but it''s on the first', 'Of course, they do', 'Yes, but it''s called "Dependence Day"', 'Yes, and it''s a celebration of American independence', 'B', NOW()),
  ('Which would be worth more, a pound of $10 pure gold coins of half a pound of $20 pure gold coins, or would they be worth the same amount?', 3, 'Think about the market value of gold', 'A pound of gold is always worth more than a half pound of gold', 'A pound of $10 pure gold coins', 'A half pound of $20 pure gold coins', 'Both would be worth the same amount', 'C', NOW()),
  ('Who is Schrödinger''s cat?', 3, 'It''s both alive and not alive, depending on your perspective.', 'A real cat', 'A thought experiment', 'A scientist''s pet', 'A cat with nine lives', 'B', NOW()),
  ('Even if they were starving, first peoples living in the Arctic never ate penguin eggs. Why not?', 3, 'The answer lies in the geographical distribution of penguins.', 'They do not like penguin eggs', 'They make you sick', 'There are not any penguins in the Arctic', 'Hard to find', 'C', NOW()),
  ('Four men were in a boat on a lake. The boat capsized and all four men sank and to the bottom of the lake, yet not a single man got wet! Why?', 3, 'Think about the wording of single man', 'They all got wet not just one single man', 'Because they were wearing scuba gear', 'They were still in the boat', 'Because they were all married', 'D', NOW()),
  ('If you divide thirty by half and add ten, what is the answer?', 3, 'When dividing by fractions, you must invert and multiply.', '70', '12', '25', '60', 'A', NOW()),
  ('Forward I am heavy, backward I am not. What am I?', 3, 'Play on words', 'Weight', 'Light', 'The word ton', 'Gravity', 'C', NOW()),
  ('How many squares on a chessboard?', 3, 'Add all squares including one of the whole board', '64 single squares', 'total of 204 square', '36 square made of 9 single squares', '9 squares made of 36 single squares', 'B', NOW()),
  ('How many 3-cent stamps are in a dozen?', 3, 'Think about how many stamps not the amount it cost', '4', '3', '12', '36', 'C', NOW()),
  ('How many cubic meters of dirt are in a hole 6 meters long, 2 meters wide, and 1 meter deep?', 3, 'Think about the nature of a hole and what it represents in terms of space and volume.', '9 meters', '1', '2', 'None', 'D', NOW()),
  ('In the following series, which numbers can be evenly divided by two? 1 2 3 4 5 6 7 8 9', 3, 'What type of numbers can be cut in half.', 'All even numbers', 'All of them', 'All odd numbers', 'None of them', 'B', NOW()),
  ('I have a foot on each end, and one in the middle. What am I?', 3, 'Consider objects that have a measurement component and are associated with length.', 'A yard stick', 'A ruler', 'A person', 'A ladder', 'A', NOW()),
  ('What is the mathematical concept behind the game of Sudoku?', 3, 'No Latin was harmed in the making of this concept.', 'Set theory', 'Group theory', 'Latin squares', 'Probability', 'C', NOW()),
  ('Which one of the three would see most clearly in total darkness? A leopard, a bat, or an owl?', 3, 'When it''s pitch black, all eyes are in the same boat.', 'leopard', 'bat', 'None', 'owl', 'C', NOW()),
  ('How can half of 12 be 7?', 3, 'Explore the world of numerals.', 'Upper half of the Roman numeral for 12 looks like the number for seven', 'If you add 5 to half of 12, you get 7', 'In a special numbering system, half of 12 is indeed 7', 'It''s a mathematical illusion, half of 12 is not really 7', 'A', NOW()),
  ('Mr. and Mrs. Clatter have five perfectly healthy children. Half of them are boys. How is that possible?', 3, 'Consider the information given carefully and think about the total number of children.', 'The family has a mix of boys and girls, but only half are mentioned', 'They adopted some of the children', 'Mrs. Clatter has a twin sister who also has children', 'The other half are also boys', 'D', NOW()),
  ('If you were to step into a sealed room filled with 100% methane gas and strike a match, what would happen?', 3, 'Think about what fire needs to exist and how it interacts with different environments.', 'It would explode', 'The match would burn briefly and then extinguish', 'To the match and the room nothing, the match cannot spark without oxygen', 'The room would catch fire but not explode', 'C', NOW()),
  ('Therein lies the secret. For you see, there is a seven-letter word in the English language that contains eight words without rearranging any of its letters. What is the word?', 3, 'Pay attention to the wording of the question', 'Wordplay', 'Puzzled', 'Therein', 'Mystery', 'C', NOW()),
  ('How can you physically stand behind your father while he is standing behind you?', 3, 'Think about spatial relationships and ways people can be positioned relative to each other.', 'Mirror', 'back to back', 'Hologram', 'Shadow', 'B', NOW()),
  ('How many mistakes can you find in the following sentence? This sentence contains four mistakes.', 3, 'One of the mistakes is the claim made in the sentence', 'Three', 'One', 'Four', 'Two', 'A', NOW()),
  ('What five-letter word becomes shorter when you add two letters to it?', 3, 'It''s a play on words and the nature of the word itself.', 'Brief', 'Short', 'Snappy', 'Little', 'B', NOW()),
  ('If you were to take two cucumbers from three cucumbers, how many would you have?', 3, 'Think about the action mentioned in the question.', 'One', 'Five', 'Two', 'Three', 'C', NOW()),
  ('Professor Quantum has two coins that total 30 cents. Since one of the coins is not a nickel what are the two coins?', 3, 'Read the question very carefully.', 'Two dimes', 'Two fifteen cent coins', 'A quarter and a nickel', 'Quarter and half a dime', 'C', NOW()),
  ('Many people consider it amazing, and just their luck, that things are always in the last place you look for them. What is wrong with this belief?', 3, 'Consider the logic of the statement.', 'It''s a universal truth', 'Once you find something, you don''t look elsewhere', 'It''s a statistical anomaly', 'It''s a self-fulfilling prophecy', 'B', NOW());