INSERT INTO vegetables (name, description, image_url, difficulty, climate, sun_required, water_time, harvest_date, space)
VALUES
('Beets', 'Beets are a root vegetable, best grown in 10-26 degrees C. They require 4-6 hours of sunlight per day, water every 3 days, and need to be spaced 4 inches apart.', '../images/vegetables/Beets.png', 2, '10-26 degrees C', 5, 3, 26, 4),
('Cabbage', 'Cabbage is a cole crop, best grown in 13-24 degrees C. They require 3-4 hours of sunlight per day, water every 3 days, and need to be spaced 1 foot apart.', '../images/vegetables/cabbage.png', 1, '13-24 degrees C', 4, 3, 27, 12),
('Celery', 'Celery is a marshland plant, best grown in 15-21 degrees C. They require 4-6 hours of sunlight per day, water every 3 days, and need to be spaced 6 inches apart.', '../images/vegetables/celery.png', 3, '15-21 degrees C', 6, 3, 22, 6),
('Onions', 'Onions are a root vegetable, best grown in 20-25 degrees C. They require 4-6 hours of sunlight per day, water every 7 days, and need to be spaced 6 inches apart.', '../images/vegetables/onions.png', 2, '20-25 degrees C', 5, 7, 36, 6),
('Potatoes', 'Potatoes are a root vegetable, best grown in 15-20 degrees C. They require 4-6 hours of sunlight per day, water every 3 days, and need to be spaced 3 feet apart.', '../images/vegetables/potatoes.png', 1, '15-20 degrees C', 5, 3, 14, 35),
('Peppers', 'Peppers come in different colors, most commonly green, yellow, and red, and are best grown in 16-28 degrees C. They require 3-4 hours of sunlight per day, (plus additional shade), water every day, and need to be spaced 2 feet apart.', '../images/vegetables/peppers.png', 2, '16-28 degrees C', 4, 3, 75, 24),
('Tomatoes', 'Tomatoes are a very common garden crop, best grown in 14-16 degrees C. They require 8 hours of sunlight per day, water every 10 days, and need to be spaced 18 inches apart.', '../images/vegetables/tomatoes.png', 2, '14-16 degrees C', 8, 10, 75, 18),
('Cauliflower', 'Cauliflower is a vegetable of the cabbage family, best grown in 15-18 degrees C. It requires 6 hours of sunlight per day, water every 3 days, and need to be spaced 2 feet apart.', '../images/vegetables/cauliflower.png', 3, '15-18 degrees C', 6, 3, 126, 24),
('Basil', 'Basil is a herb, best grown in 18-30 degrees C. It requires 7 hours of sunlight per day, water once a week, and needs to be spaced 1 foot apart.', '../images/vegetables/basil.png', 1, '18-30 degrees C', 7, 7, 56, 12),
('Summer Squash', 'Squash come in both summer and winter varieties, summer squash is best grown in 15-28 degrees C. They 6-8 hours of sunlight per day, water every 3 days, and need to be spaced 4 feet apart.', '../images/vegetables/squash.png', 1, '15-28 degrees C', 7, 3, 168, 48),
('Carrots', 'Carrots are root vegetables, best grown in 10-28 degrees C. They require 7 hours of sunlight per day, water every 3 days, and need to be spaced 2 inches apart.', 'bloom-client/src/assets/images/vegetables/carrots.png', 2, '10-28 degrees C', 7, 1, 32, 2),
('Radishes', 'Radishes are fast growing root vegetables, best grown in 18-30 degrees C. They require 3 hours of sunlight per day, water every 3 days, and need to be spaced 4 feet apart.', '../images/vegetables/radish.png', 3, '18-30 degrees C', 3, 3, 24, 2),
('Strawberry', 'Strawberries are bright red fruits, best grown in 20-29 degree C. They require 6 hours of sunlight per day, water every day, and need to be spaced 4 feet apart.', '../images/vegetables/strawberry.png', 1, '20-29 degrees C', 6, 1, 38, 2),
('Cucumber', 'Cucumbers are an easy-care vegetable, best grown in 15-30 degrees C. They require 5 hours of sunlight per day, water once a week, and need to be spaced 2-3 feet apart.', '../images/vegetables/cucumbers.png', 2, '15-30 degrees C', 6, 7, 100, 30),
('Green Bean', 'Green Beans are a garden staple, best grown in 18-29 degrees C. They require 1-2 hours of sunlight per day, water once a week and need to be spaced 3 inches apart.', '../images/vegetables/grn-beans.png', 2, '18-29 degrees C', 2, 7, 126, 3);
