INSERT INTO vegetables (name, description, image_url, avatar_url, difficulty, depth, climate, sun_required, water_time, harvest_date, space)
VALUES
('Beets', 'Beets are a root vegetable that provide some impressive health benefits. Not to mention, they are low in calories and a great source of nutrients, including fiber, folate and vitamin C. Beets also contain nitrates and pigments that may help lower blood pressure and improve athletic performance.', '../images/vegetables/Beets.png', '../images/avatars/cartoon-beet.png', 2, 1, '10-26 degrees C', 5, 3, 26, 4),
('Cabbage', 'Cabbage is a cole crop, best grown in 13-24 degrees C. They require 3-4 hours of sunlight per day, water every 3 days, and need to be spaced 1 foot apart.', '../images/vegetables/cabbage.png', '../images/avatars/cartoon-cabbage.png', 1, 1, '13-24 degrees C', 4, 3, 27, 12),
('Celery', 'Celery is a marshland plant, best grown in 15-21 degrees C. They require 4-6 hours of sunlight per day, water every 3 days, and need to be spaced 6 inches apart.', '../images/vegetables/celery.png', '../images/avatars/cartoon-celery.png', 3, 0.5, '15-21 degrees C', 6, 3, 22, 6),
('Onions', 'Onions are root vegetables that contain antioxidants and compounds that fight inflammation, decrease triglycerides and reduce cholesterol levels. Their potent anti-inflammatory properties may also help reduce high blood pressure and protect against blood clots. They will also be the unappreciated star of every meal.', '../images/vegetables/onions.png', '../images/avatars/cartoon-onion.png', 2, 1, '20-25 degrees C', 5, 7, 36, 6),
('Potatoes', 'Potatoes are a root vegetable, best grown in 15-20 degrees C. They require 4-6 hours of sunlight per day, water every 3 days, and need to be spaced 3 feet apart.', '../images/vegetables/potatoes.png', '../images/avatars/cartoon-potato.png', 1, 15, '15-20 degrees C', 5, 3, 14, 35),
('Peppers', 'Peppers come in different colors, most commonly green, yellow, and red, and are best grown in 16-28 degrees C. They require 3-4 hours of sunlight per day, (plus additional shade), water every day, and need to be spaced 2 feet apart.', '../images/vegetables/peppers.png', '../images/avatars/cartoon-pepper.png', 2, 0.5, '16-28 degrees C', 4, 3, 75, 24),
('Tomatoes', 'Tomatoes are a very common garden crop, best grown in 14-16 degrees C. They require 8 hours of sunlight per day, water every 10 days, and need to be spaced 18 inches apart.', '../images/vegetables/tomatoes.png', '../images/avatars/cartoon-tomato.png', 2, 0.3, '14-16 degrees C', 8, 10, 75, 18),
('Cauliflower', 'Cauliflower is a vegetable of the cabbage family, best grown in 15-18 degrees C. It requires 6 hours of sunlight per day, water every 3 days, and need to be spaced 2 feet apart.', '../images/vegetables/cauliflower.png', '../images/avatars/cartoon-cauliflower.png', 3, 0.5, '15-18 degrees C', 6, 3, 126, 24),
('Basil', 'Basil is a herb, best grown in 18-30 degrees C. It requires 7 hours of sunlight per day, water once a week, and needs to be spaced 1 foot apart.', '../images/vegetables/basil.png', '../images/avatars/cartoon-basil.png', 1, 1, '18-30 degrees C', 7, 7, 56, 12),
('Summer Squash', 'Squash come in both summer and winter varieties, summer squash is best grown in 15-28 degrees C. They 6-8 hours of sunlight per day, water every 3 days, and need to be spaced 4 feet apart.', '../images/vegetables/squash.png', '../images/avatars/cartoon-squash.png', 1, 2, '15-28 degrees C', 7, 3, 168, 48),
('Carrots', 'Carrots are root vegetables, best grown in 10-28 degrees C. They require 7 hours of sunlight per day, water every 3 days, and need to be spaced 2 inches apart.', '../images/vegetables/carrots.png', '../images/avatars/cartoon-carrot.png', 2, 5, '10-28 degrees C', 7, 1, 32, 2),
('Radishes', 'Radishes are fast growing root vegetables, best grown in 18-30 degrees C. They require 3 hours of sunlight per day, water every 3 days, and need to be spaced 4 feet apart.', '../images/vegetables/radish.png', '../images/avatars/cartoon-radish.png', 3, 0.5, '18-30 degrees C', 3, 3, 24, 2),
('Strawberry', 'Strawberries are packed with vitamin C, fiber, antioxidants, and more. The heart-shaped silhouette of the strawberry is the first clue that this fruit is good for you. These potent little packages protect your heart, increase good cholesterol, lower your blood pressure, and guard against cancer.', '../images/vegetables/strawberry.png', '../images/avatars/cartoon-strawberry.png', 1, 0.3, '20-29 degrees C', 6, 1, 38, 2),
('Cucumber', 'Cucumbers are an easy-care vegetable, best grown in 15-30 degrees C. They require 5 hours of sunlight per day, water once a week, and need to be spaced 2-3 feet apart.', '../images/vegetables/cucumbers.png', '../images/avatars/cartoon-cucumber.png', 2, 2, '15-30 degrees C', 6, 7, 100, 30),
('Green Bean', 'Green Beans are a garden staple, best grown in 18-29 degrees C. They require 1-2 hours of sunlight per day, water once a week and need to be spaced 3 inches apart.', '../images/vegetables/grn-beans.png', '../images/avatars/cartoon-bean.png', 2, 4, '18-29 degrees C', 2, 7, 126, 3);
