INSERT INTO exercises (name, type, muscle, equipment, difficulty, image, instructions)
VALUES
('Back Squat', 'strength', 'Quadriceps', 'barbell, rack', 'medium', 'https://images.pexels.com/photos/371049/pexels-photo-371049.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'From a standing position, keep your core tight and place your feet shoulder-width apart, toes pointing outward slightly. Slowly lower your body by bending the knees until your quads are parallel to the floor (or even a little lower), keeping your chest up and back straight.'),
('Barbell Bench Press', 'strength', 'Pectoralis major', 'barbell, bench', 'medium', 'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'While lying on a flat bench, grip the barbell with hands slighly wider than shoulder width. Slowly lift the bar off the rack, then lower the bar to the chest around nipple level. Press up while keeping your core engaged and feet planted.'),
('Lat Pulldown', 'strength', 'Latissimus dorsi', 'cable pulley machine', 'easy', 'https://images.pexels.com/photos/9614530/pexels-photo-9614530.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Sit on the seat and adjust the thigh support so that it holds you firmly in place. Grab the bar with a wider than shoulder width grip and pull down while bringing your elbows in towards your hips.'),
('Romanian Deadlift', 'strength', 'Hamstrings', 'barbell', 'hard', 'https://images.pexels.com/photos/4608145/pexels-photo-4608145.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Stand with your feet shoulder-width apart. Hold the bar in front of the thighs. Hinge at the hips while keeping the core engaged and the back straight. Lower the bar while keeping a slight bend in the knees until you feel a good stretch in the hamstrings.'),
('Dip', 'strength', 'Triceps', 'dip bars', 'medium', 'https://images.unsplash.com/photo-1598267416809-5c73f1b24404?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=737&q=80', 'Hold onto the dip bars and jump up to straighten your arms. You should be suspended in the air, held only by your arms. Lower your body by bending at the elbows until your shoulder are at the same height as your elbows. Push back up.'),
('Standing Calf Raise', 'strength', 'Calves', 'step or block', 'easy', 'https://images.pexels.com/photos/8436687/pexels-photo-8436687.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Stand on any surface with your heels hanging off. Contract your calves by pointing your toes and shifting your weight to the ball of your feet. Come down slowly and let the calves fully stretch before contracting again.'),
('Dumbell Supinated Curl', 'strength', 'Biceps', 'dumbells', 'easy', 'https://images.pexels.com/photos/6455960/pexels-photo-6455960.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Stand up straight holding the dumbells by your side. Bend one arm at a time while rotating your wrist so that your palm faces up. Bring the dumbell up to about chest height and lower in a controlled manner.'),
('Deadlift', 'strength', 'Hamstrings', 'barbell', 'hard', 'https://images.unsplash.com/photo-1534368270820-9de3d8053204?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'Standing with your feet shoulder-width apart, grasp the bar with your hands just outside your legs. Lift the bar by driving your hips forwards, keeping a flat back. Lower the bar under control.'),
('Overhead Press', 'strength', 'Deltoids', 'barbell', 'medium', 'https://images.pexels.com/photos/2628215/pexels-photo-2628215.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Stand with your body upright and core muscles braced, looking straight ahead. Hold the bar on your upper chest, gripping it with hands just wider than shoulder-width apart. Press the bar directly overhead. Don''t tilt your hips forward during the move.'),
('Chest-supported T-bar Row', 'strength', 'Latissimus dorsi', 't-bar machine', 'medium', 'https://images.unsplash.com/photo-1598575435247-2572be03bf6d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', 'Get in position on the machine with your chest braced against the support. Pull the handles back towards the side of your torso while keeping your body straight.'),
('Leg Extension', 'strength', 'Quadriceps', 'leg extension machine', 'easy', 'https://cdn.pixabay.com/photo/2021/01/19/12/29/academy-5931069_960_720.jpg', 'Get in position on the seat and adjust the ankle support so that there''s resistance when you try to extend the knees. Extend the knees until they''re straight and slowly release.'),
('Cable Flye', 'strength', 'Pectoralis', 'dual cable pulley machine', 'easy', 'https://images.pexels.com/photos/5327505/pexels-photo-5327505.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Grab one handle in each hand and start with your arms out to your sides. Bring your arms together in front of you by contracting your chest and keeping a slight bend in the elbows.'),
('Crunch', 'strength', 'Abdominals', 'mat', 'easy', 'https://images.pexels.com/photos/6392835/pexels-photo-6392835.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Lie on your back with your knees bent towards the ceiling. Raise your upper body by contracting your abs. Hold your feet under optional support for more stability.'),
('Barbell Skullcrusher', 'strength', 'Triceps', 'barbell, bench', 'medium', 'https://images.pexels.com/photos/3837743/pexels-photo-3837743.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Lie down on the bench and hold the barbell above your chest. Keep your upper arms stationary as you bring the bar down towards your forehead. Extend the triceps to return to the starting position.'),
('Dumbbell Walking Lunge', 'strength', 'Quadriceps', 'dumbbells', 'medium', 'https://images.pexels.com/photos/8032831/pexels-photo-8032831.jpeg?auto=compress&cs=tinysrgb&w=1600', 'Stand up straight with a dumbbell in each hand. Feet are a little less than shoulder-width apart. Take a big step forward and lower your body until the opposite knee approaches the floor. Remain balanced. Stand back up by bringing your hind leg forward and repeat.'),
('Dumbbell Incline Press', 'strength', 'Pectoralis minor', 'dumbbells', 'easy', 'https://images.pexels.com/photos/14036074/pexels-photo-14036074.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Set the bench to about a 45 degree incline. Get in position with your feet on the ground and hold the dumbbells near your shoulders. Push up until they almost touch and bring them back down fully.'),
('Chin Up', 'strength', 'Latissimus dorsi', 'pull up bar', 'medium', 'https://images.pexels.com/photos/12005631/pexels-photo-12005631.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Grab the bar with a supinated (palms facing you), shoulder width grip. Pull yourself up until your chin is above the bar. Release slowly. Use resistance bands or a machine if you need assistance.'),
('Hip Thrust', 'strength', 'Glutes', 'barbell, bench', 'easy', 'https://images.pexels.com/photos/7674486/pexels-photo-7674486.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Sit on the floor with your upper back against a bench. Roll the barbell onto your hip crease and plant your feet flat on the ground. Thrust your hips up by contracting your glutes.'),
('Face Pull', 'strength', 'Posterior Deltoids', 'cable pulley machine, rope attachment', 'easy', 'https://images.pexels.com/photos/3839053/pexels-photo-3839053.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Attach the rope to the cable machine near eye-level. Stand a few steps away from the machine so your arms are extended in front of you when holding the ends of the rope. With your elbows pointed out towards your sides, pull the rope back past your head, as if you''re trying to point behind you with your thumbs.'),
('Dumbbell Lateral Raise', 'strength', 'Lateral Deltoids', 'dumbbells', 'easy', 'https://images.pexels.com/photos/3839506/pexels-photo-3839506.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Stand up straight with your feet shoulder width apart. Hold the dummbells by your sides and raise your arms until they''re parallel to the floor. Keep a slight bend in your elbows and lower them back down slowly.'),
('Leg Curl', 'strength', 'Hamstrings', 'leg curl machine', 'easy', 'https://images.pexels.com/photos/13878760/pexels-photo-13878760.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Sit on the machine and adjust the knee and ankle supports so that you feel resistance when you try to bend your knees. Contract your hamstrings until your knees are bent to about 90 degrees and slowly release.');




