INSERT INTO reviews (building_id, user_id, area_id, title, building_rating, area_rating, comment, landlord_rating, recommend_to_friend)
VALUES
(114, 1, 1,'This place is amazing!', 5, 5, 'Great building with great ammenties around the building. Landlord is sensational!', true, true),
(114, 2, 1,'This place is an Oasis!', 5, 5, 'Beautiful building and friendly neighbours. Building Manager is so kind!', true, true),
(114, 4, 1,'I love this place!', 5, 5, 'The landlord is so sweet. The rent is a bit pricey though!', true, false),
(114, 3, 1, 'Great place to live!', 5, 5, 'Ammentities are amazing, great view, great landlord', true, true),
(114, 5, 2, 'Best of the Bay Area!', 5, 5, 'My husband and I have lived in the community for quite some time and we can say this is the best apartment in the area.', true, true),
(114, 6, 2, 'What a gem!', 5, 5, 'So lucky to have found this spot. Rent is still affordable and building is superb! Landlord rocks!', true, true),
(114, 7, 2,'Happy Here!', 5, 5, 'Great building with all the amenities. Area is good, but does get noisy at times!', true, false),
(114, 8, 2, 'Best place ever!', 5, 5, 'I enjoy living at this community. It is central to many things and is part of a vibrant neighborhood.', true, true),
(114, 9, 2, 'Five stars!', 5, 5, 'Great place to live. Apartments are modern, updated, and have great views all over. Location is great as well.', false, true),
(114, 10, 2, 'The perfect place to live', 5, 5, 'Amentities are amazing, great view, great landlord.', true, true),
(114, 11, 2, 'No complaints!', 5, 5, 'Happy with everything here. The landlord makes a mean brownie!', true, true),

(52, 21, 1,'This place is dingy!', 1, 2, 'Apartment is run down, but rent is cheap. The area has everything you need which is why I stay. Landlord disappeared.', false, false),
(52, 22, 1,'You get what you pay for', 2, 2, 'We had a leak and the landlord never fixed it. The rent is cheap though.', false, true),
(52, 23, 1, 'Buyers Beware!', 2, 2, 'The apartment might be nice but the surronding area is just so distracting and noisy! The landlord does not fix anything around here.', false, false),
(52, 24, 1, 'Dont move here!!', 1, 2, 'The staff is horrible and will ignore any and all maintenance requests. The residents are loud, and play loud music at the pool agains the rules, and the staff apparently wants it do be that chaotic all the time. ', false, false),
(52, 25, 1, 'Stay away!', 2, 2, 'The management is crooked and the tenants are noisy! The worst experience ever', false, false),
(52, 26, 1, 'Getting worse!', 2, 2, 'My husband and I have lived in the community for quite some time and have been greatly disappointed the last few years.', false, true),


(111, 31, 3,'What a gem!', 5, 5, 'So lucky to have found this spot. Rent is still affordable and building is superb! Landlord rocks!', true, true),
(111, 32, 4,'Mi Casa Forever!', 4, 5, 'I have lived here for 10 years and will never leave. Such a clean building and the views are incredible. Area is spectacular! Landlord is to die for!', true, true),
(111, 33, 2, 'Best place ever!', 4, 4, 'I enjoy living at this community. It is central to many things and is part of a vibrant neighborhood.', true, false),
(111, 33, 2, 'This place is amazing!', 3, 2, 'Great building with great ammenties around the building. Landlord is sensational!', true, false),
(111, 34, 1,'Could use some work!', 2, 3, 'Landlords are trust worthy however area is lacking amentities', false, false),

(112, 41, 1, 'Buyers Beware!', 1, 2, 'The apartment might be nice but the surronding area is just so distracting and noisy! The landlord does not fix anything around here.', false, false),
(113, 42, 2,'Happy Here!', 5, 2, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(114, 43, 1,'Mi Casa Forever!', 5, 5, 'I have lived here for 10 years and will never leave. Such a clean building and the views are incredible. Area is spectacular! Landlord is to die for!', true, true),
(115, 44, 1,'This place is dingy!', 2, 4, 'Apartment is run down, but rent is cheap. The area has everything you need which is why I stay. Landlord disappeared.', false, false),
(116, 45, 1,'This place is an Oasis!', 4, 4, 'Beautiful building and friendly neighbours. Building Manager is so kind!', true, true),
(117, 46, 1,'You get what you pay for', 2, 2, 'We had a leak and the landlord never fixed it. The rent is cheap though.', false, true),
(118, 47, 1,'Could use some work!', 3, 3, 'Landlords are trust worthy however area is lacking amentities', false, false),
(119, 48, 1,'What a gem!', 3, 4, 'So lucky to have found this spot. Rent is still affordable and building is superb! Landlord rocks!', true, false),
(120, 49, 1,'Happy Here!', 4, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(121, 50, 1, 'Buyers Beware!', 2, 2, 'The apartment might be nice but the surronding area is just so distracting and noisy! The landlord does not fix anything around here.', false, false),
(122, 51, 2,'Happy Here!', 4, 2, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(123, 52, 1,'Mi Casa Forever!', 4, 5, 'I have lived here for 10 years and will never leave. Such a clean building and the views are incredible. Area is spectacular! Landlord is to die for!', true, true),
(124, 53, 1,'This place is dingy!', 2, 4, 'Apartment is run down, but rent is cheap. The area has everything you need which is why I stay. Landlord disappeared.', false, false),
(125, 54, 1,'This place is an Oasis!', 4, 4, 'Beautiful building and friendly neighbours. Building Manager is so kind!', true, true),
(126, 55, 1,'You get what you pay for', 2, 2, 'We had a leak and the landlord never fixed it. The rent is cheap though.', false, true),
(127, 56, 1,'Could use some work!', 3, 3, 'Landlords are trust worthy however area is lacking amentities', false, false),
(128, 57, 1,'What a gem!', 4, 4, 'So lucky to have found this spot. Rent is still affordable and building is superb! Landlord rocks!', true, false),
(129, 58, 1,'Happy Here!', 4, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(130, 59, 1,'Happy Here!', 4, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),

(130, 41, 1, 'Buyers Beware!', 1, 2, 'The apartment might be nice but the surronding area is just so distracting and noisy! The landlord does not fix anything around here.', false, false),
(131, 42, 2,'Happy Here!', 4, 2, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(132, 43, 1,'Mi Casa Forever!', 3, 5, 'I have lived here for 10 years and will never leave. Such a clean building and the views are incredible. Area is spectacular! Landlord is to die for!', true, true),
(133, 44, 1,'This place is dingy!', 2, 4, 'Apartment is run down, but rent is cheap. The area has everything you need which is why I stay. Landlord disappeared.', false, false),
(134, 45, 1,'This place is an Oasis!', 4, 4, 'Beautiful building and friendly neighbours. Building Manager is so kind!', true, true),
(135, 46, 1,'You get what you pay for', 2, 2, 'We had a leak and the landlord never fixed it. The rent is cheap though.', false, true),
(136, 47, 1,'Could use some work!', 3, 3, 'Landlords are trust worthy however area is lacking amentities', false, false),
(137, 48, 1,'What a gem!', 3, 4, 'So lucky to have found this spot. Rent is still affordable and building is superb! Landlord rocks!', true, false),
(138, 49, 1,'Happy Here!', 4, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(139, 50, 1, 'Buyers Beware!', 2, 2, 'The apartment might be nice but the surronding area is just so distracting and noisy! The landlord does not fix anything around here.', false, false),

(140, 51, 2,'Happy Here!', 4, 2, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(141, 52, 1,'Mi Casa Forever!', 4, 5, 'I have lived here for 10 years and will never leave. Such a clean building and the views are incredible. Area is spectacular! Landlord is to die for!', true, true),
(142, 53, 1,'This place is dingy!', 2, 4, 'Apartment is run down, but rent is cheap. The area has everything you need which is why I stay. Landlord disappeared.', false, false),
(143, 54, 1,'This place is an Oasis!', 4, 4, 'Beautiful building and friendly neighbours. Building Manager is so kind!', true, true),
(144, 55, 1,'You get what you pay for', 2, 2, 'We had a leak and the landlord never fixed it. The rent is cheap though.', false, true),
(145, 56, 1,'Could use some work!', 3, 3, 'Landlords are trust worthy however area is lacking amentities', false, false),
(146, 57, 1,'What a gem!', 1, 4, 'So lucky to have found this spot. Rent is still affordable and building is superb! Landlord rocks!', true, false),
(147, 58, 1,'Happy Here!', 1, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(148, 59, 1,'Happy Here!', 4, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(149, 33, 2, 'This place is amazing!', 3, 2, 'Great building with great ammenties around the building. Landlord is sensational!', true, false),
(140, 34, 1,'Could use some work!', 2, 3, 'Landlords are trust worthy however area is lacking amentities', false, false),

(150, 51, 2,'Happy Here!', 4, 2, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(151, 52, 1,'Mi Casa Forever!', 4, 5, 'I have lived here for 10 years and will never leave. Such a clean building and the views are incredible. Area is spectacular! Landlord is to die for!', true, true),
(152, 53, 1,'This place is dingy!', 2, 4, 'Apartment is run down, but rent is cheap. The area has everything you need which is why I stay. Landlord disappeared.', false, false),
(153, 54, 1,'This place is an Oasis!', 4, 4, 'Beautiful building and friendly neighbours. Building Manager is so kind!', true, true),
(154, 55, 1,'You get what you pay for', 2, 2, 'We had a leak and the landlord never fixed it. The rent is cheap though.', false, true),
(155, 56, 1,'Could use some work!', 3, 3, 'Landlords are trust worthy however area is lacking amentities', false, false),
(156, 57, 1,'What a gem!', 1, 4, 'So lucky to have found this spot. Rent is still affordable and building is superb! Landlord rocks!', true, false),
(157, 58, 1,'Happy Here!', 1, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(158, 59, 1,'Happy Here!', 4, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(159, 33, 2, 'This place is amazing!', 3, 2, 'Great building with great ammenties around the building. Landlord is sensational!', true, false),
(150, 34, 1,'Could use some work!', 2, 3, 'Landlords are trust worthy however area is lacking amentities', false, false),

(160, 51, 2,'Happy Here!', 4, 2, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(161, 52, 1,'Mi Casa Forever!', 4, 5, 'I have lived here for 10 years and will never leave. Such a clean building and the views are incredible. Area is spectacular! Landlord is to die for!', true, true),
(162, 53, 1,'This place is dingy!', 2, 4, 'Apartment is run down, but rent is cheap. The area has everything you need which is why I stay. Landlord disappeared.', false, false),
(163, 54, 1,'This place is an Oasis!', 4, 4, 'Beautiful building and friendly neighbours. Building Manager is so kind!', true, true),
(164, 55, 1,'You get what you pay for', 2, 2, 'We had a leak and the landlord never fixed it. The rent is cheap though.', false, true),
(165, 56, 1,'Could use some work!', 3, 3, 'Landlords are trust worthy however area is lacking amentities', false, false),
(166, 57, 1,'What a gem!', 1, 4, 'So lucky to have found this spot. Rent is still affordable and building is superb! Landlord rocks!', true, false),
(167, 58, 1,'Happy Here!', 1, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(168, 59, 1,'Happy Here!', 4, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(169, 33, 2, 'This place is amazing!', 3, 2, 'Great building with great ammenties around the building. Landlord is sensational!', true, false),
(160, 34, 1,'Could use some work!', 2, 3, 'Landlords are trust worthy however area is lacking amentities', false, false),

(170, 51, 2,'Happy Here!', 4, 2, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(171, 52, 1,'Mi Casa Forever!', 4, 5, 'I have lived here for 10 years and will never leave. Such a clean building and the views are incredible. Area is spectacular! Landlord is to die for!', true, true),
(172, 53, 1,'This place is dingy!', 2, 4, 'Apartment is run down, but rent is cheap. The area has everything you need which is why I stay. Landlord disappeared.', false, false),
(173, 54, 1,'This place is an Oasis!', 4, 4, 'Beautiful building and friendly neighbours. Building Manager is so kind!', true, true),
(174, 55, 1,'You get what you pay for', 2, 2, 'We had a leak and the landlord never fixed it. The rent is cheap though.', false, true),
(175, 56, 1,'Could use some work!', 3, 3, 'Landlords are trust worthy however area is lacking amentities', false, false),
(176, 57, 1,'What a gem!', 1, 4, 'So lucky to have found this spot. Rent is still affordable and building is superb! Landlord rocks!', true, false),
(177, 58, 1,'Happy Here!', 1, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(178, 59, 1,'Happy Here!', 4, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(179, 33, 2, 'This place is amazing!', 3, 2, 'Great building with great ammenties around the building. Landlord is sensational!', true, false),
(170, 34, 1,'Could use some work!', 2, 3, 'Landlords are trust worthy however area is lacking amentities', false, false),


(01, 82, 2,'Happy Here!', 4, 2, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(02, 83, 1,'Mi Casa Forever!', 4, 5, 'I have lived here for 10 years and will never leave. Such a clean building and the views are incredible. Area is spectacular! Landlord is to die for!', true, true),
(03, 84, 1,'This place is dingy!', 2, 4, 'Apartment is run down, but rent is cheap. The area has everything you need which is why I stay. Landlord disappeared.', false, false),
(04, 85, 1,'This place is an Oasis!', 4, 4, 'Beautiful building and friendly neighbours. Building Manager is so kind!', true, true),
(05, 86, 1,'You get what you pay for', 2, 2, 'We had a leak and the landlord never fixed it. The rent is cheap though.', false, true),
(06, 87, 1,'Could use some work!', 3, 3, 'Landlords are trust worthy however area is lacking amentities', false, false),
(07, 88, 1,'What a gem!', 3, 4, 'So lucky to have found this spot. Rent is still affordable and building is superb! Landlord rocks!', true, false),
(08, 89, 1,'Happy Here!', 4, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(09, 80, 1, 'Buyers Beware!', 2, 2, 'The apartment might be nice but the surronding area is just so distracting and noisy! The landlord does not fix anything around here.', false, false),
(10, 81, 2,'Happy Here!', 4, 2, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),

(11, 82, 1,'Mi Casa Forever!', 4, 5, 'I have lived here for 10 years and will never leave. Such a clean building and the views are incredible. Area is spectacular! Landlord is to die for!', true, true),
(12, 83, 1,'This place is dingy!', 2, 4, 'Apartment is run down, but rent is cheap. The area has everything you need which is why I stay. Landlord disappeared.', false, false),
(13, 84, 1,'This place is an Oasis!', 4, 4, 'Beautiful building and friendly neighbours. Building Manager is so kind!', true, true),
(14, 85, 1,'You get what you pay for', 2, 2, 'We had a leak and the landlord never fixed it. The rent is cheap though.', false, true),
(15, 86, 1,'Could use some work!', 3, 3, 'Landlords are trust worthy however area is lacking amentities', false, false),
(16, 87, 1,'What a gem!', 4, 4, 'So lucky to have found this spot. Rent is still affordable and building is superb! Landlord rocks!', true, false),
(17, 88, 1,'Happy Here!', 4, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(18, 89, 1,'Happy Here!', 4, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(19, 83, 2, 'This place is amazing!', 3, 2, 'Great building with great ammenties around the building. Landlord is sensational!', true, false),
(20, 84, 1,'Could use some work!', 2, 3, 'Landlords are trust worthy however area is lacking amentities', false, false),

(31, 82, 1,'Mi Casa Forever!', 4, 5, 'I have lived here for 10 years and will never leave. Such a clean building and the views are incredible. Area is spectacular! Landlord is to die for!', true, true),
(32, 83, 1,'This place is dingy!', 2, 4, 'Apartment is run down, but rent is cheap. The area has everything you need which is why I stay. Landlord disappeared.', false, false),
(33, 84, 1,'This place is an Oasis!', 4, 4, 'Beautiful building and friendly neighbours. Building Manager is so kind!', true, true),
(34, 85, 1,'You get what you pay for', 2, 2, 'We had a leak and the landlord never fixed it. The rent is cheap though.', false, true),
(35, 86, 1,'Could use some work!', 3, 3, 'Landlords are trust worthy however area is lacking amentities', false, false),
(36, 87, 1,'What a gem!', 4, 4, 'So lucky to have found this spot. Rent is still affordable and building is superb! Landlord rocks!', true, false),
(37, 88, 1,'Happy Here!', 4, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(38, 89, 1,'Happy Here!', 4, 4, 'Great building with all the amenities. Area is good, but does have a few sketchy parts!', true, false),
(39, 83, 2, 'This place is amazing!', 3, 2, 'Great building with great ammenties around the building. Landlord is sensational!', true, false),
(40, 84, 1,'Could use some work!', 2, 3, 'Landlords are trust worthy however area is lacking amentities', false, false);