DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS expenses CASCADE;
DROP TABLE IF EXISTS savings CASCADE;
DROP TABLE IF EXISTS add_savings CASCADE;


CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  income_amount INTEGER NOT NULL
);

CREATE TABLE categories (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE expenses (
	id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
	created_at DATE NOT NULL,
	amount_spent INTEGER NOT NULL,
	category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE
);

CREATE TABLE savings (
	id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
	name VARCHAR(255) NOT NULL,
	total_amount INTEGER NOT NULL
);

CREATE TABLE add_savings (
	id SERIAL PRIMARY KEY NOT NULL,
  saving_id INTEGER REFERENCES savings(id) ON DELETE CASCADE,
	amount INTEGER NOT NULL,
	created_at DATE NOT NULL
);







