DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS resources CASCADE;
DROP TABLE IF EXISTS favourites CASCADE;


CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE posts (
  id SERIAL PRIMARY KEY NOT NULL,
  body VARCHAR(255) NOT NULL,
  time_stamp DATE NOT NULL DEFAULT CURRENT_DATE,
  isDeleted BOOLEAN NOT NULL DEFAULT FALSE,
  user_id INTEGER REFERENCES users(id)
);

CREATE TABLE resources (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  link VARCHAR(255) NOT NULL,
  content VARCHAR(255) NOT NULL,  /* description */
  favourited BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE favourites (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id),
  resource_id INTEGER REFERENCES resources(id)
);
