DROP TABLE IF EXISTS test CASCADE;
DROP TABLE IF EXISTS phil CASCADE;


CREATE TABLE test (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE phil (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);