DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS bookclubs CASCADE;
DROP TABLE IF EXISTS finished_books CASCADE;
DROP TABLE IF EXISTS members CASCADE;
DROP TABLE IF EXISTS meetings CASCADE;
DROP TABLE IF EXISTS current_reads CASCADE;
DROP TABLE IF EXISTS want_to_reads CASCADE;
DROP TABLE IF EXISTS have_reads CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(50) NOT NULL,
  image_url TEXT NOT NULL
);

CREATE TABLE bookclubs (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  private BOOLEAN NOT NULL,
  image_url TEXT NOT NULL,
  current_book INT DEFAULT NULL
);

CREATE TABLE finished_books (
  id SERIAL PRIMARY KEY NOT NULL,
  club_id INTEGER REFERENCES bookclubs(id) ON DELETE CASCADE,
  isbn INT DEFAULT NULL
);

CREATE TABLE members (
  id SERIAL PRIMARY KEY NOT NULL,
  club_id INTEGER REFERENCES bookclubs(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE meetings (
  id SERIAL PRIMARY KEY NOT NULL,
  club_id INTEGER REFERENCES bookclubs(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  time TIME NOT NULL,
  virtual_link TEXT NOT NULL,
  notes TEXT DEFAULT NULL,
  complete BOOLEAN DEFAULT FALSE
);

CREATE TABLE current_reads (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  isbn INT DEFAULT NULL,
  api TEXT NOT NULL
);

CREATE TABLE want_to_reads (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  isbn INT DEFAULT NULL,
  api TEXT NOT NULL
);

CREATE TABLE have_reads (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  isbn INT DEFAULT NULL,
  api TEXT NOT NULL
);