DROP TABLE IF EXISTS artworks CASCADE;

CREATE TABLE artworks (
  id SERIAL PRIMARY KEY NOT NULL,
  author_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  link VARCHAR(255) NOT NULL,
  descrip VARCHAR(255) NOT NULL,
  for_sale BOOLEAN NOT NULL,
  price INTEGER DEFAULT NULL
);
