DROP TABLE IF EXISTS posts CASCADE;
CREATE TABLE posts ( 
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  photo TEXT NOT NULL,
  description TEXT NOT NULL,
  topic VARCHAR(255) NOT NULL,
  number_of_likes INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL
);