DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE garden_vegs (
id SERIAL PRIMARY KEY NOT NULL,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
vegetable_id INTEGER REFERENCES vegetables(id) ON DELETE CASCADE,
plot_id INTEGER REFERENCES plots(id) ON DELETE CASCADE,
planted_date TIMESTAMP,
);