DROP TABLE IF EXISTS plots_vegs CASCADE;
CREATE TABLE plots_vegs (
id SERIAL PRIMARY KEY NOT NULL,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
vegetable_id INTEGER REFERENCES vegetables(id) ON DELETE CASCADE,
plot_id INTEGER REFERENCES plots(id) ON DELETE CASCADE,
planted_date TIMESTAMP
);