DROP TABLE IF EXISTS user_plants CASCADE;
CREATE TABLE user_plants ( 
  id SERIAL PRIMARY KEY,
  species_id INTEGER REFERENCES species(species_id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  nickname VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NULL
);