DROP TABLE IF EXITS veg_baskets CASCADE; 
CREATE TABLE veg_baskets (
id SERIAL PRIMARY KEY NOT NULL,
vegetable_id INTEGER REFERENCES vegetables(id) ON DELETE CASCADE,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
plot_id INTEGER REFERENCES plots(id) ON DELETE CASCADE,
);