DROP TABLE IF EXISTS comments CASCADE;
CREATE TABLE comments ( 
  id SERIAL PRIMARY KEY NOT NULL,
  post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
  comment_user_id INTEGER REFERENCES users(id) ON DELETE CASCADE, 
  comment_text VARCHAR(255)
);